################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
dsplib/source/vector/msp_abs_iq31.obj: ../dsplib/source/vector/msp_abs_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_abs_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_abs_q15.obj: ../dsplib/source/vector/msp_abs_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_abs_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_add_iq31.obj: ../dsplib/source/vector/msp_add_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_add_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_add_q15.obj: ../dsplib/source/vector/msp_add_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_add_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_add_iq31.obj: ../dsplib/source/vector/msp_cmplx_add_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_add_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_add_q15.obj: ../dsplib/source/vector/msp_cmplx_add_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_add_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_conj_iq31.obj: ../dsplib/source/vector/msp_cmplx_conj_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_conj_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_conj_q15.obj: ../dsplib/source/vector/msp_cmplx_conj_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_conj_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_mac_iq31.obj: ../dsplib/source/vector/msp_cmplx_mac_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_mac_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_mac_q15.obj: ../dsplib/source/vector/msp_cmplx_mac_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_mac_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_mpy_iq31.obj: ../dsplib/source/vector/msp_cmplx_mpy_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_mpy_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_mpy_q15.obj: ../dsplib/source/vector/msp_cmplx_mpy_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_mpy_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_mpy_real_iq31.obj: ../dsplib/source/vector/msp_cmplx_mpy_real_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_mpy_real_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_mpy_real_q15.obj: ../dsplib/source/vector/msp_cmplx_mpy_real_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_mpy_real_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_scale_iq31.obj: ../dsplib/source/vector/msp_cmplx_scale_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_scale_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_scale_q15.obj: ../dsplib/source/vector/msp_cmplx_scale_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_scale_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_shift_iq31.obj: ../dsplib/source/vector/msp_cmplx_shift_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_shift_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_shift_q15.obj: ../dsplib/source/vector/msp_cmplx_shift_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_shift_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_sub_iq31.obj: ../dsplib/source/vector/msp_cmplx_sub_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_sub_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_cmplx_sub_q15.obj: ../dsplib/source/vector/msp_cmplx_sub_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_cmplx_sub_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_mac_iq31.obj: ../dsplib/source/vector/msp_mac_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_mac_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_mac_q15.obj: ../dsplib/source/vector/msp_mac_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_mac_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_max_iq31.obj: ../dsplib/source/vector/msp_max_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_max_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_max_q15.obj: ../dsplib/source/vector/msp_max_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_max_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_max_uq15.obj: ../dsplib/source/vector/msp_max_uq15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_max_uq15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_max_uq31.obj: ../dsplib/source/vector/msp_max_uq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_max_uq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_min_iq31.obj: ../dsplib/source/vector/msp_min_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_min_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_min_q15.obj: ../dsplib/source/vector/msp_min_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_min_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_min_uq15.obj: ../dsplib/source/vector/msp_min_uq15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_min_uq15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_min_uq31.obj: ../dsplib/source/vector/msp_min_uq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_min_uq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_mpy_iq31.obj: ../dsplib/source/vector/msp_mpy_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_mpy_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_mpy_q15.obj: ../dsplib/source/vector/msp_mpy_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_mpy_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_neg_iq31.obj: ../dsplib/source/vector/msp_neg_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_neg_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_neg_q15.obj: ../dsplib/source/vector/msp_neg_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_neg_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_offset_iq31.obj: ../dsplib/source/vector/msp_offset_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_offset_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_offset_q15.obj: ../dsplib/source/vector/msp_offset_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_offset_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_scale_iq31.obj: ../dsplib/source/vector/msp_scale_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_scale_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_scale_q15.obj: ../dsplib/source/vector/msp_scale_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_scale_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_shift_iq31.obj: ../dsplib/source/vector/msp_shift_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_shift_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_shift_q15.obj: ../dsplib/source/vector/msp_shift_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_shift_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_sub_iq31.obj: ../dsplib/source/vector/msp_sub_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_sub_iq31.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/vector/msp_sub_q15.obj: ../dsplib/source/vector/msp_sub_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/vector/msp_sub_q15.d_raw" --obj_directory="dsplib/source/vector" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '


