/*
 * isr.h
 *
 *  Created on: 17 Feb 2018
 *
 */

#ifndef ISR_ISR_H_
#define ISR_ISR_H_

// the maximum number of events (generated by ISRs) which
// are not processed by the corresponding thread
#define MAX_PENDING_INTERRUPTS  8

#include "isrmanager.h"
#include "persistentqueue.h"

// checks if the thread event slots are not full
#define __EVENT_BUFFER_FULL(threadid)   \
    __event_buffer_full_ISR(__get_thread(threadid))

// signaling of the event from ISRs
#define __SIGNAL_EVENT(threadid,event)  \
    __event_signal_ISR(__get_thread(threadid),event)

#endif /* ISR_ISR_H_ */
