################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
dsplib/source/filter/msp_biquad_cascade_df1_q15.obj: ../dsplib/source/filter/msp_biquad_cascade_df1_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/filter/msp_biquad_cascade_df1_q15.d_raw" --obj_directory="dsplib/source/filter" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/filter/msp_biquad_cascade_df2_ext_q15.obj: ../dsplib/source/filter/msp_biquad_cascade_df2_ext_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/filter/msp_biquad_cascade_df2_ext_q15.d_raw" --obj_directory="dsplib/source/filter" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/filter/msp_biquad_cascade_df2_q15.obj: ../dsplib/source/filter/msp_biquad_cascade_df2_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/filter/msp_biquad_cascade_df2_q15.d_raw" --obj_directory="dsplib/source/filter" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/filter/msp_biquad_df1_q15.obj: ../dsplib/source/filter/msp_biquad_df1_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/filter/msp_biquad_df1_q15.d_raw" --obj_directory="dsplib/source/filter" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/filter/msp_biquad_df2_ext_q15.obj: ../dsplib/source/filter/msp_biquad_df2_ext_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/filter/msp_biquad_df2_ext_q15.d_raw" --obj_directory="dsplib/source/filter" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/filter/msp_biquad_df2_q15.obj: ../dsplib/source/filter/msp_biquad_df2_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/filter/msp_biquad_df2_q15.d_raw" --obj_directory="dsplib/source/filter" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/filter/msp_cmplx_fir_iq31.obj: ../dsplib/source/filter/msp_cmplx_fir_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/filter/msp_cmplx_fir_iq31.d_raw" --obj_directory="dsplib/source/filter" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/filter/msp_cmplx_fir_q15.obj: ../dsplib/source/filter/msp_cmplx_fir_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/filter/msp_cmplx_fir_q15.d_raw" --obj_directory="dsplib/source/filter" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/filter/msp_fir_iq31.obj: ../dsplib/source/filter/msp_fir_iq31.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/filter/msp_fir_iq31.d_raw" --obj_directory="dsplib/source/filter" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '

dsplib/source/filter/msp_fir_q15.obj: ../dsplib/source/filter/msp_fir_q15.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/opt/ti/ccsv8/ccs_base/msp430/include" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu/msp430" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar/dsplib" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/channel" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/isr" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/mcu" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/scheduler" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK/timer" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/InkMerge/InK" --include_path="/home/dpatoukas/Documents/TUDelft/Thesis/Ink++/InKApplications/powercast_ar" --include_path="/opt/ti/ccsv8/tools/compiler/ti-cgt-msp430_18.1.1.LTS/include" --advice:power=all --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="dsplib/source/filter/msp_fir_q15.d_raw" --obj_directory="dsplib/source/filter" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: "$<"'
	@echo ' '


